Develop
LenaChaldina/java-filmorate pull request #11
Opened 2022-12-09 13:15 UTC by LenaChaldina

Все смерджено для общей проверки

2022-12-10 17:48 UTC, ErkinKasymaliev requested changes
уууфф, привет, наконец-то проверил.
Прошу обратить внимание на комменты, которые я оставил в в storage-х где "...update() возвращает кол-во измененных строк". Проверьте все dbstorage-ы.

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    private Integer id;
Давайте все классы в пакете модель приведем к одному шаблону: у вас private выставлены через аннотации, в другом стоит private, где то есть @Id, в других нет, на некоторых id стоит final, где-то отступы есть, где лепите сразу друг за другом. Возьмите какой-нибудь класс за эталонный, остальные приведите под него.

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/mappers/MpaMapper.java
> +
слишком много отступов и есть неиспользуемые импорты. Возьмите за пример DirectorMapper и поправьте все классы в этом пакете. Лишние импорты убираются Сtrl+Alt+O

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorStorage.java
> +package ru.yandex.practicum.filmorate.dao;
в этом пакете давайте тоже у всех интерфейсов уберем лишние импорты и сделаем единые отступы у методов

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +@Component("directorDbStorage")
в это пакете где то @Component где-то @Repository, где-то есть логгирование. 
Оставьте везде @Repository, логгирование, также есть ли есть неиспользуемые импорты - уберите их. Не забудьте про отступы.

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    Integer id = 1;
почему нет модификатора доступа?

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    final DirectorDbStorage directorDbStorage;
почему нет модификатора доступа?

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (checkContainsDirectorInList(id)) {
зачем здесь проверять наличие? getDirectorById вернет null, если нет такого пользователя, null и обработайте.  Тем более checkContainsDirectorInList делает запрос в бд - это уже лишний запрос.

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (checkContainsDirectorInList(director.getId())) {
зачем здесь проверять наличие? jdbcTemplate.update() возвращает кол-во строк, которые были изменены. Если он возвращает <1, значит с таким id режиссера не нашлось в таблице и ничего не обновилось. Используйте эту информацию. Тем более checkContainsDirectorInList делает запрос в бд - это уже лишний запрос.

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (!checkContainsDirectorInList(id)) {
зачем здесь проверять наличие? jdbcTemplate.update() возвращает кол-во строк, которые были изменены. Если он возвращает <1, значит с таким id режиссера не нашлось в таблице и ничего не обновилось. Используйте эту информацию. Тем более checkContainsDirectorInList делает запрос в бд - это уже лишний запрос.

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (checkContainsDirectorInList(director.getId())) {
Этот коммент и 2 ниже относятся ко всем классам в пакете service

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        Collection<Integer> filmIdList = jdbcTemplate.query("SELECT FILMS_LIKES.film_id, COUNT(FILMS_LIKES.like_id)\n" +
вот так не надо делать. Сделайте все в одном запросе с join-ми и отсортируйте там же

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +            films.add(findFilmById(sqlRowSet.getInt("film_id")));
вот так не надо делать. Сделайте все в одном запросе с join-ми.

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDbStorage.java
> +    public List<Feed> getFeedByUserId(int userId) {
здесь норм

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDbStorage.java
> +        eventToNumDictionary = new HashMap<>();
зачем вот это все???

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDbStorage.java
> +        Map<String, Integer> data = ValidationEventData(parameters, eventType, operation);
вы очень усложнили! вам нужно тут просто реализовать insert. 
сделайте аргумент в методе addFeedEvent  просто Feed. дальнейший вызов метода  примерно будет выглядеть так:


class SomeService {
     private final FeeStorage storage;
     
     ...
     ....

     storage.addFeedEvent( new Feed(userId, entityId, EventType.Like, OperationType.Add);
--вместо entityeId вставляйте id лайка, отзыва или еще чего то,

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDbStorage.java
> +    private Map<String, Integer> ValidationEventData(Map<String, Integer> parameters, EventType eventType, OperationType operation) {
не нужен

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        feedStorage.addFeedEvent(Map.of("userId", userId, "entityId", id), EventType.LIKE, OperationType.REMOVE);
смотрите коммент в FeedDbStorage

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        likeStorage.checkFilmId(id);
в likeStorage.deleteLike вы тоже проверяете наличие фильма и юзера, ни там ни здесь это не нужно, как я уже писал jdbcTemplate.update() возвращает кол-во измененных строк.

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
>          if (getSqlRowSetByFilmId(id).next()) {
проверка не нужна

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +            removeFilmGenres(id);
эти все методы давайте вызывать в FilmService

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        if (getUsersSqlRowSet(id).next()) {
проверка не нужна

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            removeUserFriends(id);
эти методы давайте вызывать в UserService

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            Mpa mpa = jdbcTemplate.queryForObject("select mpa_dictionary.mpa_id, mpa_dictionary.rating from mpa_dictionary where mpa_id =?", new MpaMapper(), film.getMpa().getId());
в цикле вы каждый раз делаете по 2 запроса, лучше вынесите Mpa mpa = jdbcTemplate.queryForObject и List<Genre> genres = jdbcTemplate.query за цикл. А в цикле уже сеттьте mpa и genres в film.

2022-12-10 17:48 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +        Set<Review> reviewForFilm = new TreeSet<>(comparator);
зачем тут компаратор, вы можете в отсортировать в запросе через order by

2022-12-11 11:41 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    private Integer id;
done (кроме @id в feed - для Марка)

2022-12-11 11:41 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/mappers/MpaMapper.java
> +
done

2022-12-11 11:48 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorStorage.java
> +package ru.yandex.practicum.filmorate.dao;
done

2022-12-11 11:52 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +@Component("directorDbStorage")
Логирование перенесено из базы на уровень бизнес-логики.

2022-12-11 12:08 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    Integer id = 1;
done

2022-12-11 12:08 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    final DirectorDbStorage directorDbStorage;
done

2022-12-11 12:51 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (checkContainsDirectorInList(id)) {
Не получилось вернуть null, направила запрос в Пачку.

2022-12-11 14:26 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (checkContainsDirectorInList(director.getId())) {
исправлено для updateDirector

2022-12-11 14:27 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (!checkContainsDirectorInList(id)) {
Не стали справлять, так как в базу сразу делается удаление, а в сервисе обработка

2022-12-11 14:35 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (!checkContainsDirectorInList(id)) {
исправили для deleteDirectorById

2022-12-11 15:24 UTC, DpaNniK commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        Collection<Integer> filmIdList = jdbcTemplate.query("SELECT FILMS_LIKES.film_id, COUNT(FILMS_LIKES.like_id)\n" +
done

2022-12-11 15:25 UTC, DpaNniK commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        feedStorage.addFeedEvent(Map.of("userId", userId, "entityId", id), EventType.LIKE, OperationType.REMOVE);
done

2022-12-11 16:09 UTC, DpaNniK commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDbStorage.java
> +        Set<Review> reviewForFilm = new TreeSet<>(comparator);
done

2022-12-11 19:32 UTC, makar182 commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    private Integer id;
в Feed также поправил

2022-12-11 20:29 UTC, makar182 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDbStorage.java
> +        eventToNumDictionary = new HashMap<>();
обсудили

2022-12-11 20:29 UTC, makar182 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDbStorage.java
> +        Map<String, Integer> data = ValidationEventData(parameters, eventType, operation);
готово

2022-12-11 20:31 UTC, makar182 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDbStorage.java
> +    private Map<String, Integer> ValidationEventData(Map<String, Integer> parameters, EventType eventType, OperationType operation) {
Проверка не нужна? Почему? Если будет попытка выполнить действие над несуществующей связкой, то в журнал событий такая несуществующая связка будет зафиксирована. Временно удалил, но хотелось бы пояснений.

2022-12-14 16:20 UTC, ErkinKasymaliev requested changes
Привет, уже очень хорошо!
Оставил пару комментов

2022-12-14 16:20 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDbStorage.java
> +            getUserIdForDeleteReviewEvent(feed);
как я понял вы тут сеттите юзера в feed. Но разве feed уже не содержит в себе userId?

2022-12-14 16:20 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +        return getDirectorById(director.getId());
здесь просто director верните, у него уже есть id. Не надо делать лишний запрос. Также поправьте в других методах create в storage-х

2022-12-14 16:20 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +            return getDirectorById(director.getId());
здесь просто director верните, у него уже есть id. Не надо делать лишний запрос. Также поправьте в других методах update в storage-х

2022-12-14 16:20 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +            throw new EntityNotFoundException("Такого режиссера нет");
хорошо

2022-12-14 16:20 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    Integer id = 1;
забыли добавить модификатор доступа

2022-12-14 16:20 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    final DirectorDbStorage directorDbStorage;
забыли добавить модификатор

2022-12-14 16:20 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Director updateDirector = directorDbStorage.updateDirector(director);
Лучше сделайте так:

        Director updateDirector = directorDbStorage.updateDirector(director);
        if (updateDirector == null) {
            log.warn("Ошибка. Режиссер не найден в списке");
            throw new RequestError(HttpStatus.NOT_FOUND
                , "Ошибка. Невозможно обновить несуществующий фильм");
        }
        log.info("Информация о режиссере обновлена {}", director.getName());
        return updateDirector;
        
так будет семантически правильнее

2022-12-14 16:20 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        if (checkContainsDirectorInList(id)) {
directorDbStorage.getDirectorById(id) не возвращает null, если поставить несуществующий id.
Должно быть так:
public Director getDirectorById(Integer id) {
            log.info("Получен запрос информации о режиссере {}", id);
            Director director = directorDbStorage.getDirectorById(id);
            
           if(director == null) {
                 log.warn("Получен запрос на не существующего в списке режиссера");
                 throw new RequestError(HttpStatus.NOT_FOUND, "Режиссер не найден");
           }
           return director;
    }

аналогично для других методов getById

2022-12-14 17:53 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +        return getDirectorById(director.getId());
исправлено в стораджах

2022-12-14 17:53 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/DirectorDbStorage.java
> +            return getDirectorById(director.getId());
готово

2022-12-14 17:57 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Director updateDirector = directorDbStorage.updateDirector(director);
исправлено

2022-12-14 18:42 UTC, LenaChaldina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Director updateDirector = directorDbStorage.updateDirector(director);
Добавила проверки на null в checkContainsDirectorInList

2022-12-14 20:17 UTC, makar182 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDbStorage.java
> +            getUserIdForDeleteReviewEvent(feed);
При удалении review передаётся только его идентификатор. Для целостности данных я по этому идентификатору для данного кейса отдельно получаю идентификатор пользователя.

2022-12-15 06:23 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FeedDbStorage.java
> +            getUserIdForDeleteReviewEvent(feed);
понял, тогда надо переделать. Удаление вы вызываете в FeedService, в этом классе и найдите userId
@Override
    public void deleteReview(int reviewId) {
        if (checkContainsReview(reviewId)) {
            log.warn("Отзыв не удален, отзыва с id {} не найдено", reviewId);
            throw new EntityNotFoundException("Отзыв с таким id не найден");
        }
        log.info("Отзыв с id = {} успешно удален", reviewId);
        l**ong userId = .....**
        if (feedStorage.addFeedEvent(Feed.builder().**userId(userId).**entityId(reviewId).eventType(EventType.REVIEW).operation(OperationType.REMOVE).build()) != 1) {
            log.warn("Ошибка добавления события entityId = {}, eventType = {}, operation = {} в ленту!",
                    reviewId,
                    EventType.REVIEW,
                    OperationType.REMOVE);
            throw new RequestError(HttpStatus.INTERNAL_SERVER_ERROR, "Событие не добавлено в ленту!");
        } else {
            log.info("Добавлено событие в ленту!");
        }
        reviewDbStorage.deleteReview(reviewId);
    }

2022-12-15 06:31 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Director updateDirector = directorDbStorage.updateDirector(director);
checkContainsDirectorInList он тут не нужен. 
вызывайте сразу directorDbStorage.getDirectorById(id);
метод checkContainsDirectorInList бесполезный, сперва вы селектике всех директоров, потом проходите в циклом и ищите нужный id. Есть же storage.getDirectorById, который делает тоже самое, но уже в бд. 
Ребят, метод должен быть удален и забыт, как и все его аналоги в других сервисах.

2022-12-15 06:34 UTC, ErkinKasymaliev requested changes
привет!
Ребят, оставил коммент полный боли и тоски в DirectorService.
если вы не прочуствуете мою боль от этого метода, тогда будем созваниваться, чтоб вы боль мою услышали.

2022-12-15 14:05 UTC, ErkinKasymaliev requested changes
Ох ты ж черт побери! Я этого почему то не увидел.
Ребята нельзя service имплементить от storage. public class DirectorService implements DirectorStorage { - вот так не пойдет. Это разные вещи.
Давайте так: просто сделайте DirectorService без имплементаций, также другие сервисы. Для 1го проекта так пойдет. В будущем же надо писать отдельный интерфейсы для сервизного слоя.

2022-12-15 14:08 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    DirectorService directorService;
здесь и в других контроллерах поставьте модификатор доступа на поля, которые инвективе

2022-12-15 15:52 UTC, ErkinKasymaliev approved these changes
Молодцы, все ошибки исправлены, работа принята, поздравляю!

2022-12-15 21:34 UTC, merged